### ISSUE TITLE
A question with "deployment_helper.py"

### ISSUE THREAD

**Issue by SUPERadonai** [yoshitomo-matsubara/head-network-distillation#69]
Hello, while I was trying to reproduce your code, I ran into some problems, can you give me some help?

First, in the code you provided, all the "runner" code doesn't seem to be about cooperative inference between the head model and the tail model, but I found this part in the "deployment_helper.py", thank you so much!

However, I have a question in the "deployment_helper.py" code:
"sensor_device" and "edge_device" are obtained from these two lines of code:
```
sensor_device = torch.device('cpu' if args.scpu else 'cuda')
edge_device = torch.device('cpu' if args.ecpu else 'cuda')
```
But according to these two lines of code, "sensor_device" and "edge_device" get the same device. 
This means that the split model is not deployed on the edge device and server respectively, which seems to be different from the description in the paper and the goal of the code, is this a mistake or something else?

Could you give me some help? Thank you!

**Comment by yoshitomo-matsubara** [comment]
Hello @AAtrump 

In our paper, we ran the split ("head" and "tail") models and measured their delays on sensor device and edge server respectively. The script to run cooperative inference is not included in this repo as the experiments were separately done by one of the other authors in our papers, and this repo is focused on model implementation and training.

`deployment_helper.py` is literally a helper script to split a model into two sections and save them. Then you will need to manually deploy and run them on sensor device and edge server separately, using your own script. The "device" you're seeing in the script is device type used for PyTorch (e.g., CPU vs. GPU), not an actual machine (computer).

**Comment by SUPERadonai** [comment]
thank you for your answer!
